# Generated by Django 4.0.3 on 2022-03-18 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('exist', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('exist', models.BooleanField(blank=True, default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.room')),
            ],
        ),
        migrations.CreateModel(
            name='Displacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_room', to='main.room')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.interior')),
                ('to_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_room', to='main.room')),
            ],
        ),
    ]
